include:
  - proxy.yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - "5000:5000"
    restart: on-failure
    env_file:
      - .env
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=db
    depends_on: ["db"]
    tty: true
  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    ports:
      - "3306:3306"
    restart: on-failure
    env_file:
      - .env   
    environment:
      - DB_HOST="%" 
